# Generated by Django 5.2.1 on 2025-06-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='file_path',
        ),
    ]
